suppress repack commands' error message
lnis-uofu/OpenFPGA pull request #1593
Opened 2024-03-06 09:01 UTC by treelin611

In Arkangel, the repack_dc file can be automatically generated from commands such as "set_clk" and "set_reset" in the PCF file. Therefore, some modifications are made in this PR to suppress the error messages for these two commands while reading pcf file.

2024-03-08 23:37 UTC, tangxifan requested changes

2024-03-08 23:37 UTC, tangxifan commented on libs/libpcf/src/io/pcf_reader.cpp
> +        } else if (word.find("set_clk") == 0 || word.find("set_reset") == 0) {
My suggestion is to add a new option ``--reduce_error_to_warning`` to the read_pcf command.

2024-10-31 20:51 UTC, tangxifan requested changes
@treelin611 Good work. Can you add a testcase? Then it should be ready to merge. Thanks  for the contribution.

2024-10-31 20:51 UTC, tangxifan commented on docs/source/manual/openfpga_shell/openfpga_commands/setup_commands.rst
> +    Reduce error to warning while reading commands in pcf file
Add a warning message to alert users that they should be very cautious when enable this option. 

See an example here: https://docs.verilogtorouting.org/en/latest/vpr/command_line_usage/#cmdoption-vpr-strict_checks

2024-10-31 20:51 UTC, tangxifan commented on libs/libpcf/src/io/pcf_reader.cpp
> +            VTR_LOG_WARN("Unknown command '%s'!\n", word.c_str());
Rephrase the message: 

```
Bypass unknown command '%s' 
```

2024-11-01 04:15 UTC, treelin611 commented on libs/libpcf/src/io/pcf_reader.cpp
> +            VTR_LOG_WARN("Unknown command '%s'!\n", word.c_str());
done!

2024-11-04 04:28 UTC, merged