Bin format
lnis-uofu/OpenFPGA pull request #1847
Opened 2024-09-29 04:43 UTC by treelin611

> ### Motivate of the pull request
> - To address an existing issue: https://rapidflex.feishu.cn/base/CXkHboiWGaT1jFsyVvFc8ejWnFb?table=tblL2xNFny00AigF&view=vewc4M3a58

> ### Describe the technical details
> #### What is currently done? #######
> - Created libopenfpgacapnproto to implement Cap'n Proto for loading and writing binary files.
> - Added functions to call Cap'n Proto builder and reader for writing to and retrieving information from binary files.
> - Called member functions from device_rr_gsb to load or generate unique block information.

> ### To be checked
> - Need a careful review of the CMakeLists.txt file for libopenfpgacapnproto to remove any redundant steps. Currently, it will generate redundant files rr_graph*: 
![image](https://github.com/user-attachments/assets/6a701d6e-e6c0-41c6-b432-2bb0a31ddc49)

2024-09-30 20:02 UTC, tangxifan requested changes
@treelin611 Good work. Minor changes are required.

2024-09-30 20:02 UTC, tangxifan commented on openfpga_flow/openfpga_shell_scripts/read_bin_write_xml_uniqueblocks_example_script.openfpga
> +write_unique_blocks --file ./write_unique_block.xml --verbose --type xml
Use a variable such as ${OPENFPGA_GROUP_TILE_CONFIG_FILE} to control the file type here. Avoid to create another openfpgashell script which has minor difference than another.

2024-09-30 20:02 UTC, tangxifan commented on openfpga_flow/openfpga_shell_scripts/read_bin_unique_blocks_full_flow_example_script.openfpga
> +read_unique_blocks --file ${READ_UNIQUE_BLOCKS_BIN} --verbose --type bin
Use a variable such as ${OPENFPGA_GROUP_TILE_CONFIG_FILE} to control the file type here. Avoid to create another openfpgashell script which has minor difference than another.

2024-09-30 20:02 UTC, tangxifan commented on openfpga_flow/openfpga_shell_scripts/write_bin_unique_blocks_full_flow_example_script.openfpga
> +write_unique_blocks --file ./write_unique_block.bin --verbose --type bin
Use a variable such as ${OPENFPGA_GROUP_TILE_CONFIG_FILE} to control the file type here. Avoid to create another openfpgashell script which has minor difference than another.

2024-10-08 02:32 UTC, treelin611 commented on openfpga/src/annotation/device_rr_gsb.cpp
> +        if (instance_coord != unique_block_coord) {
This is an optimization of PR#1810. This change excludes the coordinates of unique blocks from the instance coordinates. Therefore, when writing the XML or binary file, there is no need to perform the same operation again, as shown below.
![image](https://github.com/user-attachments/assets/d2d93fdd-bfb4-4426-b0c6-67a55fbb7cc3)

2024-10-08 02:33 UTC, treelin611 commented on openfpga/src/annotation/device_rr_gsb.cpp
> +        if (instance_coord != unique_block_coord) {
This is an optimization of PR#1810. This change excludes the coordinates of unique blocks from the instance coordinates. Therefore, when writing the XML or binary file, there is no need to perform the same operation again, as shown below.
![image](https://github.com/user-attachments/assets/d2d93fdd-bfb4-4426-b0c6-67a55fbb7cc3)

2024-10-08 02:33 UTC, treelin611 commented on openfpga/src/annotation/device_rr_gsb.cpp
> +        if (instance_coord != unique_block_coord) {
This is an optimization of PR#1810. This change excludes the coordinates of unique blocks from the instance coordinates. Therefore, when writing the XML or binary file, there is no need to perform the same operation again, as shown below.
![image](https://github.com/user-attachments/assets/d2d93fdd-bfb4-4426-b0c6-67a55fbb7cc3)

2024-10-08 18:43 UTC, tangxifan requested changes

2024-10-08 18:43 UTC, tangxifan commented on libs/libopenfpgacapnproto/CMakeLists.txt
> +    libopenfpgautil
Add the capnproto library from vpr: libvtrcapnproto as one of the target link library. You can avoid to duplicate the files mmap_file.cpp|h and serdes_utils.cpp|h

2024-10-09 06:31 UTC, treelin611 commented on libs/libopenfpgacapnproto/gen/unique_blocks_uxsdcxx.capnp
> +@0xa136dddfdd48783b;
I just modified the code to enable auto-generating Cap'n Proto files using an XSD file as input. The code changes are included in this PR, and the details are as follows:

1. Wrote unique_blocks.xsd to define the file format.
2. Modified CMakeLists.txt to call uxsdcxx for generating the Cap'n Proto file with the XSD file as input.
3. Modified the read & write binary functions to adapt to the auto generated data structure names

2024-10-09 09:50 UTC, treelin611 commented
Here are the main updates:
1. The auto-generation of the Cap'n Proto file is included in this PR.
2. I also added a cross-test case to read a binary file and write an XML file. The written XML file is consistent with the one generated using the write_uniqueblocks command with the type set to XML.
3. The CMakeList.txt file has been cleaned up by linking the libvtrcapnproto library.

2024-10-09 16:28 UTC, Tulong4Dev approved these changes
Looks good.

2024-10-09 20:19 UTC, tangxifan approved these changes
LGTM

2024-10-09 20:19 UTC, merged