Yosys plugin support
lnis-uofu/OpenFPGA pull request #371
Opened 2021-09-07 11:52 UTC by kkumar23

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [yes ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] VPR
> - [ ] Tileable routing architecture generator
> - [ ] OpenFPGA libraries
> - [ ] FPGA-Verilog
> - [ ] FPGA-Bitstream
> - [ ] FPGA-SDC
> - [ ] FPGA-SPICE
> - [ ] Flow scripts
> - [ ] Architecture library
> - [ ] Cell library
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2021-09-20 11:05 UTC, lnsharma requested changes

2021-09-20 11:05 UTC, lnsharma commented on openfpga.sh
> +
This addition to PATH is no longer required. You may revert changes to this file.

2021-09-20 11:05 UTC, lnsharma commented on README.md
> +source openfpga.sh
Not required now.

2021-09-20 11:05 UTC, lnsharma commented on README.md
> +Getting Started with OpenFPGA <img src="./docs/source/overview/figures/OpenFPGA_logo.png" width="200" align="right">
What is the change here?

2021-09-20 11:05 UTC, lnsharma commented on .github/workflows/build.yml
>            chmod +x openfpga/openfpga
I think in the distribution share folder where yosys-plugin so and other files are present, should also be part of distribution.

2021-09-20 11:08 UTC, lnsharma reviewed
wget needs to be installed. So, for CI run this should be present as prerequisite requirement.

2021-09-21 18:11 UTC, tangxifan commented
@kkumar23  Can you update the dependency list at https://github.com/lnis-uofu/OpenFPGA/blob/master/.github/workflows/install_dependencies_build.sh, where ``wget`` should be added.

2021-09-21 18:12 UTC, tangxifan commented
@kkumar23 Also, is there any dependencies between this PR and the other https://github.com/lnis-uofu/OpenFPGA/pull/368 ? Just need to know which one to merge first once CI is green.

2021-10-07 21:10 UTC, coolbreeze413 commented
@ganeshgore For this PR to pass CI, we would need wget to be installed on the docker containers used to execute the linux_build.

The CI executes linux_build on the containers : ghcr.io/lnis-uofu/openfpga-build-${{ matrix.config.cc}} which would have the dependencies from .github/workflows/install_dependencies_build.sh installed.
As the master branch install_dependencies_build.sh does not contain wget, the containers do not have these installed as well.

We would need to add wget to the dependencies, merge to master, then create the docker images ( I see that docker images are manually triggered as workflow_dispatch is the event for docker.yml jobs), and then this PR can pass CI.

Please let me know if you would like me to raise new PR for adding wget.

2021-10-08 04:50 UTC, ganeshgore commented
@coolbreeze413  Thanks for your PRs, I need some time to debug the issue. I will update you as soon as I have any updates.

2021-10-08 05:15 UTC, coolbreeze413 commented
@ganeshgore Thanks for merging the PR to add wget to the install dependencies.

I see that the linux_build for this PR has started passing now, so I believe the docker images for CI have also got rebuilt.
I think that I need to make changes to this PR branch https://github.com/lnis-uofu/OpenFPGA/tree/yosys_plugin_support before the pull_request check can also pass, to eliminate conflicts with master now.

Please let me know how I could get access to push changes to this branch? (Kishor was originally working on this branch, however I would be taking over that work, and need access to push to these branches to updated them)

2021-10-08 05:26 UTC, ganeshgore commented
Yes, the docker images are updated now, it has `curl` and `wget` installed. 
I cloned this PR branch `yosys_plugin_support_clone` and merged it with the master, and currently, CI is still running here
https://github.com/lnis-uofu/OpenFPGA/actions/runs/1319026649

If this turns green, we could do either of these 2 things
1. If you access to `yosys_plugin_support` branch you can merge with master and commit
2. If not, and if there are no more changes expected in this PR, we can close this PR and merge `yosys_plugin_support_clone`  branch to master

Let me know what you think 
FYI: I am giving you write permission to the repo, so you can work with this repo directly

2021-10-08 05:29 UTC, coolbreeze413 commented
Thanks!
I believe some more changes should be done to this PR before we can merge, let me discuss this further and update the status to you.

2021-10-08 15:45 UTC, ganeshgore commented
@coolbreeze413 
You need to accept the invitation to start pushing changes to this repository, please check your email. 
![image](https://user-images.githubusercontent.com/6169914/136585831-0a00e891-4dde-485e-b965-a85760c15360.png)

2021-10-08 23:12 UTC, coolbreeze413 commented
Remaining Issues are all regression test failures:
- iwls_benchmark_reg_test : opt_rmdff
- vtr_benchmark_reg_test: opt_rmdff
- micro_benchmark_reg_test: opt_rmdff
- fpga_verilog_reg_test: opt_rmdff
- quicklogic_reg_test: failing at upload artifact?
- fpga_bitstream_reg_test: failed to run ACE2
- basic_reg_test: VVP Verification Failed

I will work with the team to understand and get proper fix for these.

2021-10-10 03:53 UTC, ganeshgore commented
@coolbreeze413 That explanation generally makes sense.
However, in an ideal scenario, I would expect the OpenFPGA repository to be agnostic to these changes and natively support only the mainstream YOSYS version instead of any other modified flavors. 

I was thinking of creating a separate actions workflow for the Quicklogic regression test, so you guys can maintain separate YOSYS scripts, without worrying about existing OpenFPGA tests (which should ideally support the mainstream YOSYS version).

@tangxifan What do you think about that?

2021-10-10 05:55 UTC, ganeshgore commented
OK great,

@coolbreeze413, you can follow these steps

1. Add Yosys installation script at this location.
https://github.com/lnis-uofu/OpenFPGA/blob/d85e55aef2556459af314012c58425296a889b1f/openfpga_flow/regression_test_scripts/quicklogic_reg_test.sh#L10

You can use git to download the YOSYS version and perform the global installation. This script will run in the  `ghcr.io/lnis-uofu/openfpga-env` docker image you can choose to install YOSYS globally or locally in the same directory.

2. Once you update that,  create file `openfpga_flow/misc/ql_tools.conf` with the following content
```
[CAD_TOOLS_PATH]
yosys_path = ${PATH:OPENFPGA_PATH}/yosys/yosys <-- set this to correct yosys installation location
abc_path = ${PATH:OPENFPGA_PATH}/yosys/yosys-abc <-- set this to correct yosys-abc installation location
```
3. Add following parameter to `[SCRIPT_PARAM_MIN_ROUTE_CHAN_WIDTH]` section of each `task.conf` file in `openfpga_flow/tasks/quicklogic_tests/*`

```
[SCRIPT_PARAM_MIN_ROUTE_CHAN_WIDTH]
flow_config=${PATH:OPENFPGA_PATH}/openfpga_flow/misc/ql_tools.conf
```
This will execute quick-logic regression tests with a different version of YOSYS.

let me know if you have any questions

2021-10-12 23:52 UTC, coolbreeze413 commented
@ganeshgore @tangxifan Thanks for the inputs and efforts to create a separate flow for Quicklogic use cases.

After going through all the makefiles again of both yosys and yosys-symbiflow-plugins, I would say that changing `make` to `make install` for yosys in the `CMakeLists.txt` look like the better way to integrate the latest yosys + yosys-symbiflow-plugins into OpenFPGA, and this is in line with mainstream yosys (https://github.com/symbiflow/yosys and https://github.com/YosysHQ/yosys have the same Makefile flow), and that is why yosys-symbiflow-plugins Makefile is written to expect yosys and yosys-config in a bin/ directory.

However, if you feel that this change is not in line with the current idea of how OpenFPGA should use yosys, I have submitted a PR to yosys-symbiflow-plugins: https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/139 to enable us to configure YOSYS_CONFIG path while building (similar to the ability introduced for YOSYS_PATH).
If this PR goes through, there does not need to be any change needed in OpenFPGA specifically for Quicklogic tests to use a separate yosys version.

I feel that separating out the yosys version for enabling only Quicklogic use cases would not be a good idea for the long term goals, so we can try to accomodate the current requirements with the above approach.

2021-10-14 00:15 UTC, coolbreeze413 commented
It would definitely be good to have a call and sync up on these changes.

Meanwhile, with the PR for yosys-symbiflow-plugins merged, I investigated the ability to keep the older OpenFPGA structure, and here is what I found:

It looks like yosys expects `make install` to be called, and this becomes important for any yosys plugin to be built.

Tracing the compilation failure through the Makefile of yosys (and common Makefile of yosys plugins):

(1) yosys Makefile requires using correct `$(PREFIX)` value, because it is defined as:
`PREFIX ?= /usr/local`
This is only useful for yosys plugins, as yosys does not directly depend on this being defined correctly.
Hence previously, we could get away with just `make` rather than a `make install` when only yosys was being built.

(2) yosys-config contains the CXX flags which contains the include paths etc, needed to build any yosys plugin.
yosys-config is generated using a template `misc/yosys-config.in` and `sed`:
```
$(PROGRAM_PREFIX)yosys-config: misc/yosys-config.in
	$(P) $(SED) -e 's#@CXXFLAGS@#$(subst -I. -I"$(YOSYS_SRC)",-I"$(DATDIR)/include",$(strip $(CXXFLAGS_NOVERIFIC)))#;' \
			-e 's#@CXX@#$(strip $(CXX))#;' -e 's#@LDFLAGS@#$(strip $(LDFLAGS) $(PLUGIN_LDFLAGS))#;' -e 's#@LDLIBS@#$(strip $(LDLIBS_NOVERIFIC))#;' \
			-e 's#@BINDIR@#$(strip $(BINDIR))#;' -e 's#@DATDIR@#$(strip $(DATDIR))#;' < $< > $(PROGRAM_PREFIX)yosys-config
```

This above indicates that yosys config expects that the includes are in: 
`$(DATDIR)/include`

and `$(DATDIR)` itself is defined as: 
`DATDIR := $(PREFIX)/share/$(PROGRAM_PREFIX)yosys`

These CXX flags are used by the yosys plugin Makefiles (`Makefile_plugin.common`, same for all yosys plugins), and hence, the include dir for them would be:
`$(PREFIX)/share/$(PROGRAM_PREFIX)yosys/include`

`$(PROGRAM_PREFIX)` is usually empty (used for prefixing all yosys-* outputs).

Hence, include path becomes: 
`$(PREFIX)/share/yosys/include `

This path does not get created with only `make` called on the yosys.

Calling `make install` on yosys actually creates this directory structure (`share/yosys/include`) and move the include files into it:
```
	$(INSTALL_SUDO) mkdir -p $(DESTDIR)$(DATDIR)
	$(INSTALL_SUDO) cp -r share/. $(DESTDIR)$(DATDIR)/.
```
Hence, yosys does expect calling `make install` and even though we have the PR for yosys-symbiflow-plugins merged, which allows us to specify YOSYS_CONFIG_PATH, this is not enough to be able to build yosys plugins within OpenFPGA.

We see the following error(s) due to the above behavior, as it would be unable to find the include files:
```
In file included from get_cells.h:23:0,
                 from design_introspection.cc:21:
get_cmd.h:23:29: fatal error: kernel/register.h: No such file or directory
compilation terminated.
make[4]: *** [design_introspection.o] Error 1
<builtin>: recipe for target 'design_introspection.o' failed
```

Hence I believe we should go back to the changes where we `make install` yosys to a specific path like yosys/install and use that throughout the flows.

2021-10-14 00:23 UTC, coolbreeze413 commented
@ganeshgore On the yosys repo to use, we should be able to use the upstream YosysHQ repo as well. 
I think that the Symbiflow yosys repo, although not bleeding edge, would be preferred, as I think the Symbiflow project supports majority of the FPGA devices and integration to the PnR stages would be maintained.
However, it would probably be better for @tpagarani to add his thoughts on this topic, and we could discuss this in more detail as well.

2021-10-14 02:53 UTC, tpagarani commented
@ganeshgore @coolbreeze413 @tangxifan In ideal situation, yes we should be using YosysHQ and even plugins should be there itself. But getting our code merged in yosys-plugins at HQ is a very long route. Also recently we have been trying to use yosys-symbiflow-plugins with YosysHQ and ran into issues. So I don't see a quick path to get YosysHQ and Yosys-symbiflow-plugins working together. So if you want to stick to YosysHQ, we won't have quicklogic architecture support working in OpenFPGA. 

@tangxifan I underestand the stand from OpenFPGA point of view to have a stable release.  In that case we have to take a call from RS point of view whether the OpenFPGA  fork there should use symbiflow based code.

2021-10-14 05:50 UTC, tangxifan commented
@tpagarani I agree on your point. 
- First of all, I do not want to deprecate any OpenFPGA's features that support QuickLogic architectures. As you see, we have used QuickLogic's Yosys for almost 1 year and set up dedicated regression tests to guarantee any code changes should not break  the support on QuickLogic architectures. **We will not change this principle in future.**
- Second, the yosys has been a pain point for a while. 
  - It has so many variants and each variant has different/new features. It is very hard for us to keep an active eye on all these versions and guarantee supports. So we have to pick a few of them
  - The compilation of time of yosys is very long, which takes 2/3 of the total compilation time of the project. So we are already considering to use pre-built Yosys binaries in our docker image and run all the regression tests.

Therefore, @ganeshgore and I come up with a solution that we should consider pre-built Yosys binaries when running all the regression tests. This can allow us
- Have a short runtime in building compatibility tests -> Short CI runs
- Deploy regression tests for different yosys versions. -> OpenFPGA supports more Yosys versions than QuickLogic Yosys versions, offering more choices for our users. For example, we will add additional docker regression tests for ``QuickLogic Yosys + OpenFPGA`` or ``Symbiflow Yosys + OpenFPGA`` to Github Actions: 

![image](https://user-images.githubusercontent.com/11499826/137259085-0609eec7-1a99-423f-be6f-43f7ee830c68.png)


**But, it does not mean we will deprecate the support on QuickLogic devices. Instead, we will enrich our regression tests for QuickLogic, by pushing more benchmarks and architectures to be tested! (Since we have reduce CI runtime by using pre-built Yosys binaries, we can use these CI runtime to run more tests)**

Let me know if your concern remains. I am open to discussion and we can arrange a meeting Friday morning 9am PST if needed.

2021-10-31 03:58 UTC, tangxifan commented
@tpagarani Done in #403 Please go ahead on the plug-in

2021-11-04 06:45 UTC, coolbreeze413 commented
Closing this PR, as #408 supersedes this on top of the mainstream YosysHQ release.

2021-11-04 06:45 UTC, closed without merging