Added GSB documentation
lnis-uofu/OpenFPGA pull request #549
Opened 2022-02-22 02:11 UTC by ganeshgore

Adding documentation for general switch box XML files 

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] VPR
> - [ ] Tileable routing architecture generator
> - [ ] OpenFPGA libraries
> - [ ] FPGA-Verilog
> - [ ] FPGA-Bitstream
> - [ ] FPGA-SDC
> - [ ] FPGA-SPICE
> - [ ] Flow scripts
> - [ ] Architecture library
> - [ ] Cell library
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2022-02-22 05:33 UTC, tangxifan requested changes

2022-02-22 05:33 UTC, tangxifan commented on docs/source/manual/file_formats/gsb_file_format.rst
> +.. _file_formats_gsb_xml:
I guess you forgot to update index.rst
As a result, I cannot preview this file in readthedocs.

2022-02-22 05:33 UTC, tangxifan commented on docs/source/manual/file_formats/gsb_file_format.rst
> +  - ``SIDE`` Not Sure
Number of sides (TOP, RIGHT, BOTTOM, LEFT) available in a RSG. Most of time, it is 4.

2022-02-22 05:33 UTC, tangxifan commented on docs/source/manual/file_formats/gsb_file_format.rst
> +  - ``nID`` Internal node ID unique for the given output channel
This is the index of the node in routing resource graph.

2022-02-22 05:33 UTC, tangxifan commented on docs/source/manual/file_formats/gsb_file_format.rst
> +  - ``sID`` Not Sure
The unique id for routing segment, which is defined in the architecture <segmentlist>

2022-04-10 13:42 UTC, tangxifan commented
@ganeshgore Remember to update the doc on the new syntax in #618

2022-08-30 17:53 UTC, tangxifan commented
@ganeshgore Can you rebase this on the current master? #747 may not be merged soon. We can merge the doc update very soon. Please check the options in #751 and update documentation accordingly.

2022-08-30 18:39 UTC, ganeshgore commented
Ok, I need to update the documentation based on your PR+ additional syntax. I will do it soon and rebase

2022-09-22 04:25 UTC, merged