Update frac_mem_32k.v
lnis-uofu/OpenFPGA pull request #849
Opened 2022-10-20 06:50 UTC by yunuseryilmaz18

> ### Motivate of the pull request
> - [X] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 1. Mixed use of non-blocking and blocking statements are unsynthesizable in Synopsys Design Compiler.
> 2. While defining a multidimensional array, the first array size is for the length and the second one is for the depth. The order for ram_a and ram_b arrays was wrong and it caused "out of bounds" error in DC.
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> It makes the design synthesizable. 
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] VPR
> - [ ] Tileable routing architecture generator
> - [ ] OpenFPGA libraries
> - [ ] FPGA-Verilog
> - [ ] FPGA-Bitstream
> - [ ] FPGA-SDC
> - [ ] FPGA-SPICE
> - [ ] Flow scripts
> - [ ] Architecture library
> - [X] Cell library
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2022-10-20 22:53 UTC, tangxifan requested changes

2022-10-20 22:53 UTC, tangxifan commented on openfpga_flow/openfpga_cell_library/verilog/frac_mem_32k.v
> +  reg [0:31] ram_a [0:9];
We have not tried this with Design Compiler yet. We verified these BRAM through iVerilog
Can you try to update other BRAM verilog files?


- https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/openfpga_cell_library/verilog/dpram16k.v

- https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/openfpga_cell_library/verilog/dpram.v

- https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/openfpga_cell_library/verilog/dpram_2048x8.v

- https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/openfpga_cell_library/verilog/dpram1k.v

- https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/openfpga_cell_library/verilog/dpram8k.v

If it works fine, I am o.k. to merge. If not, we should add pre-processing flags before merging like: 

```
`ifdef SNPS_DC
  reg [0:31] ram_a[0:9];
`else
  reg [0:9] ram_a [0:31]
`endif
```

2022-10-21 13:56 UTC, yunuseryilmaz18 commented on openfpga_flow/openfpga_cell_library/verilog/frac_mem_32k.v
> +  reg [0:31] ram_a [0:9];
Hello, I wrote a testbench to analyze the design. I've added the testbench and the vcd file in my message: 
[frac_mem_32_tb.zip](https://github.com/lnis-uofu/OpenFPGA/files/9839590/frac_mem_32_tb.zip)


As a result, the design in the master does not work in iverilog:
![image](https://user-images.githubusercontent.com/30428379/197212565-0dfca2e7-144d-4b9d-bcec-c712be05baf3.png)

Also, the memory definitions are correct according to Verilog-2005 standards and similar to my PR in the designs you've shared.

2022-10-21 16:42 UTC, tangxifan commented on openfpga_flow/openfpga_cell_library/verilog/frac_mem_32k.v
> +  reg [0:31] ram_a [0:9];
o.k. Please adapt other verilog files related to BRAM. I will merge this PR then

2022-10-24 10:44 UTC, yunuseryilmaz18 commented on openfpga_flow/openfpga_cell_library/verilog/frac_mem_32k.v
> +  reg [0:31] ram_a [0:9];
I've changed some of them, how to add my changes in this PR? Or should I open another PR?

2022-10-24 17:14 UTC, tangxifan commented
@yunuseryilmaz18 Feel free to add changes to this PR.

2022-10-27 06:49 UTC, yunuseryilmaz18 commented
> @yunuseryilmaz18 Feel free to add changes to this PR.

#864 I've opened a new PR. Can you review it?

2022-10-30 19:15 UTC, tangxifan approved these changes

2022-10-30 19:15 UTC, merged